// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIP5hfB_AbGyhKkHSLXjnLJ2MnmxAsFS0',
    appId: '1:438996362141:web:c45e737b6431512b8ac574',
    messagingSenderId: '438996362141',
    projectId: 'papergames-1dc20',
    authDomain: 'papergames-1dc20.firebaseapp.com',
    databaseURL: 'https://papergames-1dc20.firebaseio.com',
    storageBucket: 'papergames-1dc20.appspot.com',
    measurementId: 'G-ZFK868Z02X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_L5UZ_QLV_dSLD_CkQuqStT51Lh9Sc4',
    appId: '1:438996362141:android:6547cf6680b89ec08ac574',
    messagingSenderId: '438996362141',
    projectId: 'papergames-1dc20',
    databaseURL: 'https://papergames-1dc20.firebaseio.com',
    storageBucket: 'papergames-1dc20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BUqp20MAY7VtQANHgmnDEAxGKHDro94',
    appId: '1:438996362141:ios:51fd52c27c78da448ac574',
    messagingSenderId: '438996362141',
    projectId: 'papergames-1dc20',
    databaseURL: 'https://papergames-1dc20.firebaseio.com',
    storageBucket: 'papergames-1dc20.appspot.com',
    iosClientId: '438996362141-nuc155kh1ihbpv9codbsu95mr1gavuj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BUqp20MAY7VtQANHgmnDEAxGKHDro94',
    appId: '1:438996362141:ios:51fd52c27c78da448ac574',
    messagingSenderId: '438996362141',
    projectId: 'papergames-1dc20',
    databaseURL: 'https://papergames-1dc20.firebaseio.com',
    storageBucket: 'papergames-1dc20.appspot.com',
    iosClientId: '438996362141-nuc155kh1ihbpv9codbsu95mr1gavuj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingoApp',
  );
}
